#!/bin/sh

set -e

# Binaries
if [ "$1" = "cli" ]; then
    # Install native dependencies
    apt update
    apt install -y curl

    # Install bagop
    curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
    install /tmp/bagop /usr/local/bin

    # Generate dependencies
    make depend

    # Build
    CGO_ENABLED=0 bagop -j "$(nproc)" -b usb-hub-configurator-cli -x '(android/*|ios/*)' -p 'make build-cli/usb-hub-configurator-cli DST=$DST' -d out

    exit 0
fi

# Frontend
if [ "$1" = "pwa" ]; then
    # Generate dependencies
    make depend

    # Build
    make build-pwa/usb-hub-configurator-pwa

    exit 0
fi
